/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pi_prog.h"


void
pi_prog_1(char *host, int passos)
{
	CLIENT *clnt;
	double  *result_1;
	teste  pi_calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PI_PROG, PI_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        
        if(passos <= 0) {
                printf("Digite um valor maior que 0\n");
                exit(1);
        }
	pi_calc_1_arg.passos = passos;
	result_1 = pi_calc_1(&pi_calc_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	else {
		printf("O Valor de pi para %d passo é: %lf\n", pi_calc_1_arg.passos, *result_1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host STEPS\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	pi_prog_1 (host, atoi(argv[2]));
exit (0);
}
