/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PI_PROG_H_RPCGEN
#define _PI_PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct teste {
	int passos;
};
typedef struct teste teste;

#define PI_PROG 0x23451111
#define PI_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define pi_calc 1
extern  double * pi_calc_1(teste *, CLIENT *);
extern  double * pi_calc_1_svc(teste *, struct svc_req *);
extern int pi_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pi_calc 1
extern  double * pi_calc_1();
extern  double * pi_calc_1_svc();
extern int pi_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_teste (XDR *, teste*);

#else /* K&R C */
extern bool_t xdr_teste ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PI_PROG_H_RPCGEN */
