/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pi_prog.h"

double *
pi_calc_1_svc(teste *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("A função de cálculo de pi foi chamada para %d passos.\n", argp->passos);

	double step;
	int i; 
	double x, sum = 0.0;
	step = 1.0/(double) argp->passos;
	for (i=0;i < argp->passos; i++){
	x = (i + 0.5) * step; // Largura do retângulo
	sum = sum + 4.0 / (1.0 + x*x);   // Sum += Área do retângulo
	}
	result = step * sum; 

	return &result;
}
