/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pi_prog.h"

bool_t
xdr_teste (XDR *xdrs, teste *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->passos))
		 return FALSE;
	return TRUE;
}
